### ISSUE TITLE
Starter Pack page is 404

### ISSUE THREAD

**Issue by TixieSalander** [vocalapp/vocalapp.github.io#7]
Hello,
Looks like the http://vocalproject.net/starter-pack page is not found

**Comment by ivanovyordan** [comment]
I can't find a Starter pack page or link. Maybe this issue should be closed?

**Comment by nathandyer** [comment]
We've removed the starter pack, and none of the recent versions of Vocal should reference it or link to it any more. I think we're safe to close this issue.
