### ISSUE TITLE
Is this the official site repo for the vocalapp? is it mirror of vocalproject.net? if so then can i contribute/make improvements to the site and fonts?

### ISSUE THREAD

**Issue by surajmandalcell** [vocalapp/vocalapp.github.io#9]
Everything is in title :stuck_out_tongue_winking_eye:

**Comment by nathandyer** [comment]
Hi! Yes, this is the repo for vocalproject.net (which is a GitHub Pages site). We certainly welcome pull requests! :) That said, I'd recommend opening an issue about the specific changes that you feel need to be made so there can be a discussion/confirmation first. I'd hate for you to put in a lot of effort only for us to reject the PR. Thanks for your willingness to help!

**Comment by surajmandalcell** [comment]
The fonts look too serif'ish(not a word) in the "Features" section so i'd like to improve that and also in the "screenshots" section the left and right button had no css so that also bothered me. Anyways ill make separate pr for each edit which i guess should work file instead of creating issues each time?
